64bits
jhunt/hex-alfred pull request #2
Opened 2020-09-30 01:43 UTC by psq

I implemented support for 64 bits numbers, if you are interested to merge it in, including the rebuilt workflow directly usable with Alfred.

2020-10-08 13:18 UTC, jhunt commented
Thanks for this!  Can you amend the PR to not include the binary workflow?  I'll compile that and verify it after I merge the PR.

2020-10-11 00:28 UTC, psq commented
PR no longer includes my rebuilt binary

2020-10-19 14:24 UTC, jhunt requested changes
Love it!  Super minor nit re: newly introduced white space.

2020-10-19 14:24 UTC, jhunt commented on hex.c
> +
```suggestion
```

2020-10-19 14:24 UTC, jhunt commented on hex.c
> +
This newline is superfluous; once it's removed we can merge this request and get it out to our legions of adoring fans. 😁

2020-10-20 23:17 UTC, psq commented on hex.c
> +
addressed in e592ce6

2020-10-29 13:12 UTC, jhunt approved these changes
LGTM

2020-10-29 13:13 UTC, merged